/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RatingCalculatorRouteImport } from './routes/rating-calculator'
import { Route as PrizeCalculatorRouteImport } from './routes/prize-calculator'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RatingCalculatorRoute = RatingCalculatorRouteImport.update({
  id: '/rating-calculator',
  path: '/rating-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrizeCalculatorRoute = PrizeCalculatorRouteImport.update({
  id: '/prize-calculator',
  path: '/prize-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prize-calculator': typeof PrizeCalculatorRoute
  '/rating-calculator': typeof RatingCalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prize-calculator': typeof PrizeCalculatorRoute
  '/rating-calculator': typeof RatingCalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prize-calculator': typeof PrizeCalculatorRoute
  '/rating-calculator': typeof RatingCalculatorRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prize-calculator' | '/rating-calculator' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prize-calculator' | '/rating-calculator' | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/prize-calculator'
    | '/rating-calculator'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrizeCalculatorRoute: typeof PrizeCalculatorRoute
  RatingCalculatorRoute: typeof RatingCalculatorRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rating-calculator': {
      id: '/rating-calculator'
      path: '/rating-calculator'
      fullPath: '/rating-calculator'
      preLoaderRoute: typeof RatingCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prize-calculator': {
      id: '/prize-calculator'
      path: '/prize-calculator'
      fullPath: '/prize-calculator'
      preLoaderRoute: typeof PrizeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrizeCalculatorRoute: PrizeCalculatorRoute,
  RatingCalculatorRoute: RatingCalculatorRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
